#!/bin/sh

battery_info=$(acpi)

battery_percentage=$(echo $battery_info | awk '{print $4}' | tr -d ',')
battery_state=$(echo "$battery_info" | awk '{print $3}' | tr -d ',')

battery_icon=''

if [ "$battery_state" = 'Charging' ]; then
    battery_symbol=''
elif [ "$battery_state" = 'Discharging' ]; then
    battery_symbol=''
elif [ "$battery_state" = 'Full' ]; then
    battery_symbol=''
fi

echo "$battery_icon$battery_percentage$battery_symbol"
