#!/bin/sh

total_ram=$(free -m | awk 'NR==2{print $2}')
used_ram=$(free -m | awk 'NR==2{print $3}')

used_ram_gb=$(echo "scale=3; $used_ram / 1024" | bc)

total_swap=$(free -m | awk 'NR==3{print $2}')
used_swap=$(free -m | awk 'NR==3{print $3}')

used_swap_gb=$(echo "scale=3; $used_swap / 1024" | bc)

memory_icon=''

echo "${memory_icon}${used_ram_gb}|${used_swap_gb}"
